<?php
require('common.php');
$code = $_POST['code'];
$action = $_POST['action'];


function generateCouponcode($length = 6) {
		$alphabets = range('A','Z');
		$numbers = range('0','9');
		$additional_characters = array('_','.');
		$final_array = array_merge($alphabets,$numbers);
			 
		$string = '';
	  
		while($length--) {
		  $key = array_rand($final_array);
		  $string .= $final_array[$key];
		}
		
			return $string;
		
}

$autoGenerated = generateCouponcode(6) ;
if($action=="Add")
{
	$sql = $db->select('tbl_promotions','couponcode',null,'couponcode ="'.$autoGenerated.'"',null);  // Table name, WHERE conditions	
}
else if($action=="Update")
{
	$id=$_POST['id'];
	$sql = $db->select('tbl_promotions','couponcode',null,'couponcode ="'.$autoGenerated.'" and id!='.$id,null);  // Table name, WHERE conditions	
}	

$res = $db->getResult(); 	
$numRows = count($res); 
	if($numRows>0)
	{
		generateCouponcode(6) ;
	}	
	else
	{
		echo generateCouponcode(6);
	}	

	
?>